apiVersion: v1
kind: Service
metadata:
  name: ineevents-backend-service
  labels:
    app: ineevents-backend
spec:
  type: ClusterIP
  selector:
    app: ineevents-backend
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http