apiVersion: v1
kind: Service
metadata:
  name: ineevents-frontend-service
  labels:
    app: ineevents-frontend
spec:
  type: NodePort
  selector:
    app: ineevents-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http